spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: MipWdnbfZaPzGNu0bD55
            client-secret: 379cEDaFOY
            redirect-uri: "https://54.180.115.224:8081/{action}/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope: name,email,nickname,gender,birthday, birthyear, mobile
            client-name: Naver
          kakao:
            #client-id == REST api KEY
            client-id: 4bd0f7d96d9da9d2b5424049f88a324a
            client-secret: 7a7ZdPGgvyu3cVZiXsgIRRuN4YbBYIw3
            redirect-uri: "https://54.180.115.224:8081/{action}/oauth2/code/{registrationId}"
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email, gender, age_range, birthday
            client-name: Kakao
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id