spring:
  datasource:
    url: jdbc:mysql://localhost:3306/studit?serverTimezone=Asia/Seoul
    username: root
    password: 8244
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-circular-references: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  thymeleaf:
    enabled: false

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

jwt:
  secret: YOUR_SECRET_KEY
  access-expired: 1800 #30(분) - 단위 (초)

