server:
  port: 8081

spring:
  profiles:
    include: oauth

  datasource:
#    url: jdbc:mysql://34.64.229.43:3306/studit?serverTimezone=Asia/Seoul
#    url: jdbc:mysql://localhost:3306/studit?serverTimezone=Asia/Seoul
    url: jdbc:mysql://studit.cp0whbx3cm7f.ap-northeast-2.rds.amazonaws.com:3306/studit?serverTimezone=Asia/Seoul
    username: root
#    password: 8244
    password: minamina
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  main:
    allow-circular-references: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true

  thymeleaf:
    enabled: false

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
  com.amazonaws.util.EC2MetadataUtils: error

jwt:
  secret: studit
  access-expired: 18000 #30(분) - 단위 (초)
 
coolsms:
  api-key: NCS2JE5WTMCHGRX5
  api-secret: VGET6RLPEAR4L2PE9BEXUIFI2UBK4Y1C
  from-number: 010-5503-8244
